--ex1
LECT NAME FROM CITY
WHERE POPULATION >120000
AND COUNTRYCODE= 'USA'
--ex2
SELECT * from CITY
WHERE COUNTRYCODE ='JPN' 
--ex3
SELECT CITY, STATE FROM STATION
--ex4

SELECT CITY FROM STATION 
WHERE CITY LIKE 'a%' 
OR CITY LIKE 'e%'
OR CITY LIKE 'i%'
OR CITY LIKE 'o%'
OR CITY LIKE 'u%'

--ex7
SELECT name  FROM Employee
ORDER BY name asc
